=== Allekzx/Centre-de-soins-XML-/src/src/data/xsd/patient.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<!--
    Document   : patient.xsd
    Created on : 22 novembre 2022, 15:13
    Author     : Léo Bouvier et Alex Delagrange
    Description:
        Ce fichier XML Schema a pour but de restreindre / structurer le
        fichier patient.xsd qui est les données d'un patient du centre
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:cab="http://www.ujf-grenoble.fr/l3miage/medical"
           targetNamespace="http://www.ujf-grenoble.fr/l3miage/medical"
           elementFormDefault="qualified">
           
    <xs:element name="patient" type="cab:Patient"/>
        
    <xs:complexType name="Patient">
        <xs:sequence>
            <xs:element name="nom" type="xs:string" minOccurs = "1" maxOccurs="1"/>
            <xs:element name="prénom" type="xs:string" minOccurs = "1" maxOccurs="unbounded"/>
            <xs:element name="sexe" type="cab:Sexe" minOccurs = "1" maxOccurs="1"/>
            <xs:element name="naissance" type="xs:date" minOccurs = "1" maxOccurs="1"/>
            <xs:element name="numéroSS" type="cab:Numéro" minOccurs = "1" maxOccurs="1"/>
            <xs:element name="adresse" type="cab:Adresse" minOccurs = "1" maxOccurs="1"/>
            <xs:element name="visite" type="cab:VisitePatient" minOccurs = "1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Adresse">
        <xs:sequence>
            <xs:element name="étage" type="xs:nonNegativeInteger" minOccurs="0" maxOccurs = "1"/>
            <xs:element name="numéro" type="xs:nonNegativeInteger" minOccurs="0" maxOccurs = "1"/>
            <xs:element name="rue" type="xs:string" minOccurs = "1" maxOccurs="1"/>
            <xs:element name="ville" type="xs:string" minOccurs = "1" maxOccurs="1"/>
            <xs:element name="codePostal" type="cab:CodePostal" minOccurs = "1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="CodePostal">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{5}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="Sexe">
        <xs:restriction base="xs:string">
            <xs:pattern value="M|F"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="Numéro">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{15}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="VisitePatient">
        <xs:sequence>
            <xs:element name="intervenant" type="cab:Intervenant"/>
            <xs:element name="acte" type="xs:string" maxOccurs = 'unbounded'/>
        </xs:sequence>
        <xs:attribute name="date" type="xs:date" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="Intervenant">
        <xs:sequence>
            <xs:element name="nom" type="xs:string" minOccurs = "1" maxOccurs="1"/>
            <xs:element name="prénom" type="xs:string" minOccurs = "1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== Allekzx/Centre-de-soins-XML-/src/src/data/xml/patient.xml
<?xml version="1.0" encoding="UTF-8"?><cab:patient xmlns:act="http://www.ujf-grenoble.fr/l3miage/actes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cab="http://www.ujf-grenoble.fr/l3miage/medical" xsi:schemaLocation="http://www.ujf-grenoble.fr/l3miage/medical ../xsd/patient.xsd">
    
    <!--
    Document   : patient.xml
    Created on : 22 novembre 2022, 15:13
    Author     : Léo Bouvier et Alex Delagrange
    Description:
        Cette instance xml du schema patient.xsd est un exemple
        de données pour un patient du centre de soins.
        Une page html a été créée pour présenter ces données (patient.html)
-->
    
    
    <cab:nom>Pien</cab:nom>
    <cab:prénom>Oscare</cab:prénom>
    <cab:sexe>F</cab:sexe>
    <cab:naissance>1975-03-25</cab:naissance>
    <cab:numéroSS>275032506569237</cab:numéroSS>
    <cab:adresse>
        <cab:rue>rue Casimir Brenier</cab:rue>
        <cab:ville>Grenoble</cab:ville>
        <cab:codePostal>38000</cab:codePostal>
    </cab:adresse>
    <cab:visite date="2015-12-08">
        <cab:intervenant>
            <cab:nom>Fréchie</cab:nom>
            <cab:prénom>Sarah</cab:prénom>
        </cab:intervenant>
        <cab:acte> 
            Prélèvement par ponction veineuse directe
        </cab:acte>
        <cab:acte>
            Inection intraveineuse directe isolée.
        </cab:acte>
    </cab:visite>
</cab:patient>

=== Allekzx/Centre-de-soins-XML-/src/data/xml/patient.xml
<?xml version="1.0" encoding="UTF-8"?><cab:patient xmlns:act="http://www.ujf-grenoble.fr/l3miage/actes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cab="http://www.ujf-grenoble.fr/l3miage/medical" xsi:schemaLocation="http://www.ujf-grenoble.fr/l3miage/medical ../xsd/patient.xsd">
    <cab:nom>Orouge</cab:nom>
    <cab:prénom>Elvire</cab:prénom>
    <cab:sexe>F</cab:sexe>
    <cab:naissance>1982-03-08</cab:naissance>
    <cab:numéro>282030802305216</cab:numéro>
    <cab:adresse>
        <cab:rue>Rond-Point de la Croix de Vie</cab:rue>
        <cab:ville>La Tronche</cab:ville>
        <cab:codePostal>38700</cab:codePostal>
    </cab:adresse>
    <cab:visite date="2015-12-08">
        <cab:intervenant>
            <cab:nom>Fréchie</cab:nom>
            <cab:prénom>Sarah</cab:prénom>
        </cab:intervenant>
        <cab:acte>
            Pansement de brûlure étendue ou de plaie chimique ou thermique étendue,
            sur une surface supérieure à 5% de la surface corporelle.
        </cab:acte>
    </cab:visite>
</cab:patient>
